### ISSUE TITLE
substr() has incorrect function signature

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/smarty_reduced_security#1]
In [line 31 of the Smarty plugin](https://github.com/eileenmcnaughton/smarty_reduced_security/blob/f37535d4a18b17259d4bc3f32ae7ec29f3a41a61/CRM/Core/Smarty/plugins/function.crmAPIWithPermissionBypass.php#L31), you have:

```php
$isGet = substr($action, strtolower($action)) !== 'get';
```

Which throws an error because the second argument is supposed to be an integer (for the offset).  Should it be this?
```php
$isGet = substr(strtolower($action), 0, 3) === 'get';
```

It wasn't working for my client (on a user-generated mailing template with Smarty enabled) so I couldn't test the fix, but it didn't throw the same error.

**Comment by eileenmcnaughton** [comment]
Yeah - good point https://github.com/eileenmcnaughton/smarty_reduced_security/commit/6dce9ebfd89aa9ceb33f846b11bb8a193dd807c7
